hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/alarm/DingSendMessageHandler.java
hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/alarm/NotifyPlatformEnum.java
hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/alarm/lark/LarkAlarmConstants.java
hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/alarm/lark/LarkSendMessageHandler.java
hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/config/MessageAlarmConfig.java
hippo4j-spring-boot-starter/src/main/resources/properties/lark/alarm.json
hippo4j-spring-boot-starter/src/main/resources/properties/lark/notice.json

feat:add lark send message handler

---

hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/alarm/lark/LarkSendMessageHandler.java
hippo4j-spring-boot-starter/src/main/resources/properties/lark/notice.json

feat:lark support notice CoreThreadTimeOut

---

hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/toolkit/HttpClientUtil.java

修正：responseBody没有关闭导致内存泄漏的问题
修正：抛出异常不够具体

修正HttpClientUtil中的内存泄漏以及优化抛出异常

---

hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/alarm/lark/LarkSendMessageHandler.java

优化飞书获取推送模板重复读取文件

---

hippo4j-spring-boot/hippo4j-spring-boot-starter/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/config/DynamicThreadPoolAutoConfiguration.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/handler/web/AbstractWebThreadPoolService.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/handler/web/JettyWebThreadPoolHandler.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/handler/web/TomcatWebThreadPoolHandler.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/starter/handler/web/UndertowWebThreadPoolHandler.java

https://github.com/acmenlt/dynamic-threadpool/issues/113
https://github.com/acmenlt/dynamic-threadpool/issues/114

add jetty、undertow ThreadPool

---

hippo4j-core/src/main/java/cn/hippo4j/core/proxy/RejectedProxyInvocationHandler.java

RejectedProxyInvocationHandler 更新 Thread pool alarm notify

Rejectedproxy update

---

hippo4j-example/hippo4j-core-zookeeper-spring-boot-starter-example/pom.xml

add hippo4j-core-zookeeper-spring-boot-starter-example pom.xml

add hippo4j-core-zookeeper-spring-boot-starter-example pom.xml

---

hippo4j-server/pom.xml

解决https://github.com/acmenlt/dynamic-threadpool/issues/152 中的问题

修复在jdk小版本中的兼容性问题

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/ThreadPoolNotifyAlarmHandler.java

空指针的优化 (#188)

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/starter/parser/ConfigFileTypeEnum.java

ConfigFileTypeEnum 枚举字段添加注释

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/starter/config/DynamicThreadPoolCoreAutoConfiguration.java

添加@ConditionalOnMissingClass，通过实际配置来加载bean，仅加载存在对应配置的bean.

close #201 : 项目中同时拥有nacso、zk依赖，默认会加载nacos和zk的RefresherHandler，导致启动报错

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/starter/config/DynamicThreadPoolCoreAutoConfiguration.java

修改@ConditionalOnProperty配置，通过配置中心子节点必存在字段判断

close #207 1.2.0-RC5版本 配置中心starter自动装配失效

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/event/ExecutorsListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/event/PlatformsListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/event/ThreadPoolDynamicRefreshEvent.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/event/ThreadPoolDynamicRefreshEventOrder.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/event/WebExecutorListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/AbstractCoreThreadPoolDynamicRefresh.java

For https://github.com/longtai-cn/hippo4j/issues/221

优化spring事件解耦

---

hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rocketmq-example/src/main/java/cn/hippo4j/springboot/starter/adapter/springcloud/stream/rocketmq/example/Hippo4jAdapterSpringCloudStreamRocketMQApplication.java

修改了 @SpringBootApplication 注解内的 scanBasePackages，使得 MessageProduce 里的 api 可以被访问到

修改了@SpringBootApplication注解的扫包

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java

feat(新增banner配置): 新增banner配置

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java

feat(新增banner配置注释): 新增banner配置注释

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java

Fixes #313
Pull Request 中提出的更改内容：
- Delete redundant comments。
> 提交 PR 前请检查邮箱设置，错误设置无法展示在贡献者列表，参考 [贡献者指南](https://hippo4j.cn/docs/other/contributor/)。

Delete redundant comments

---

hippo4j-auth/pom.xml

Pull Request 中提出的更改内容：
- POM delete default packaging
> 提交 PR 前请检查邮箱设置，错误设置无法展示在贡献者列表，参考 https://hippo4j.cn/docs/other/contributor

POM delete default packaging

---

hippo4j-common/pom.xml

- Delete redundant POM configuration.

Delete redundant POM configuration

---

hippo4j-core/pom.xml

#321 pom多余配置删除

---

hippo4j-common/pom.xml

Fixes #317
- Modify Chinese comments in hippo4j-common pom to English

Modify Chinese comments in hippo4j-common pom to English

---

hippo4j-config/pom.xml

Delete blank lines

---

docs/docs/getting-started/hippo4j-core-start.md

修改hippo4j-core文档的小错误

---

docs/docs/intro.md

update intro add hertzbeat link

---

hippo4j-example/hippo4j-example-core/pom.xml

delete name tag

---

hippo4j-common/pom.xml

remove commons-codec dependency version

---

hippo4j-console/src/main/java/cn/hippo4j/console/controller/ThreadPoolController.java
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-web/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-web/src/main/java/cn/hippo4j/springboot/starter/adapter/web/WebAdapterAutoConfiguration.java

Fixed tomcat thread pool compatibility issues

---

README.md
docs/docs/intro.md

- Modify developer contribution map.
-
-

Modify developer contribution map

---

hippo4j-discovery/pom.xml

- Delete POM Unnecessary Config
-
-

Delete POM Unnecessary Config

---

.github/FUNDING.yml

- Change appreciation link
> Check mailbox configuration when submitting. https://hippo4j.cn/docs/community/contributor

Change appreciation link

---

docs/docusaurus.config.js

Update docusaurus.config.js-hippo4j 官网修改底部加群链接 #369

---

hippo4j-auth/src/main/java/cn/hippo4j/auth/filter/JWTAuthenticationFilter.java
hippo4j-auth/src/main/java/cn/hippo4j/auth/service/impl/UserDetailsServiceImpl.java

Fix NullPointerException when logging in

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/pom.xml
pom.xml

Fixes #389
- Version number unified root POM file (#389)

Version number unified root POM file (#389)

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/ConfigHandlerConfiguration.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java

Fixes #374
- Hippo4j core configuration center validation judgment reconstruction

Hippo4j core configuration center validation judgment reconstruction

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/notify/CoreNotifyConfigBuilder.java

Fixes https://github.com/opengoofy/hippo4j/issues/399
fix: 配置中心未配置线程池启动报错，增加判空，提前返回

 Fixed #399 配置中心未配置线程池启动报错 

---

hippo4j-message/src/main/java/cn/hippo4j/message/platform/DingSendMessageHandler.java
hippo4j-message/src/main/java/cn/hippo4j/message/platform/LarkSendMessageHandler.java
hippo4j-message/src/main/java/cn/hippo4j/message/platform/WeChatSendMessageHandler.java
hippo4j-message/src/main/java/cn/hippo4j/message/platform/constant/DingAlarmConstants.java
hippo4j-message/src/main/java/cn/hippo4j/message/platform/constant/LarkAlarmConstants.java
hippo4j-message/src/main/java/cn/hippo4j/message/platform/constant/WeChatAlarmConstants.java

- Notification alarm constant class migration

Notification alarm constant class migration

---

README.md

fixed url of README.md

---

hippo4j-message/src/main/java/cn/hippo4j/message/dto/NotifyConfigDTO.java
hippo4j-message/src/main/java/cn/hippo4j/message/service/HippoBaseSendMessageService.java
hippo4j-message/src/main/java/cn/hippo4j/message/service/ThreadPoolNotifyAlarm.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/notify/CoreNotifyConfigBuilder.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/ExecutorsListener.java

Fixes #407
- Notify related parameters to add dynamic change function (#407)

Notify related parameters to add dynamic change function (#407)

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/DynamicThreadPoolExecutor.java

Fixes #405
- Fix executeTimeOut corner case exception (#405)

Fix executeTimeOut corner case exception

---

hippo4j-example/hippo4j-core-nacos-spring-boot-starter-example/src/main/resources/bootstrap.properties

- Supplementary thread pool monitoring collection type

Supplementary thread pool monitoring collection type

---

hippo4j-example/hippo4j-core-nacos-spring-boot-starter-example/pom.xml

Sample program packaging

---

pom.xml

fix issue 410

---

hippo4j-example/hippo4j-core-nacos-spring-boot-starter-example/src/main/resources/bootstrap.properties
hippo4j-monitor/hippo4j-monitor-base/pom.xml
hippo4j-monitor/hippo4j-monitor-base/src/main/java/com/example/monitor/base/AbstractDynamicThreadPoolMonitor.java
hippo4j-monitor/hippo4j-monitor-base/src/main/java/com/example/monitor/base/DynamicThreadPoolMonitor.java
hippo4j-monitor/hippo4j-monitor-base/src/main/java/com/example/monitor/base/MonitorTypeEnum.java
hippo4j-monitor/hippo4j-monitor-base/src/main/java/com/example/monitor/base/ThreadPoolMonitor.java
hippo4j-monitor/hippo4j-monitor-log/pom.xml
hippo4j-monitor/hippo4j-monitor-log/src/main/java/cn/hippo4j/monitor/log/LogMonitorHandler.java
hippo4j-monitor/hippo4j-monitor-prometheus/pom.xml
hippo4j-monitor/hippo4j-monitor-prometheus/src/main/java/cn/hippo4j/monitor/prometheus/PrometheusMonitorHandler.java
hippo4j-monitor/pom.xml
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/pom.xml
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/BootstrapCoreProperties.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/MonitorHandlerConfiguration.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/condition/LogMonitorCondition.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/condition/PrometheusMonitorCondition.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/monitor/DynamicThreadPoolMonitorExecutor.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/config/BootstrapProperties.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/config/DynamicThreadPoolAutoConfiguration.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/config/MonitorHandlerConfiguration.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/config/condition/PrometheusMonitorCondition.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/monitor/ReportingEventExecutor.java
pom.xml

Fixes #361 Fixes #386
- Dynamic thread pool monitoring module refactoring (#361)
- hippo4j server 支持多种线程池监控方式 (#386)

Dynamic thread pool monitoring module refactoring (#361) (#386)

---

hippo4j-example/hippo4j-spring-boot-starter-example/src/main/resources/META-INF/services/cn.hippo4j.core.spi.CustomRejectedExecutionHandler

Fixes #422
- Add Deny Policy Custom Example (#422)

Add Deny Policy Custom Example (#422)

---

pom.xml

- Change version number 1.4.0-SNAPSHOT

Change version number 1.4.0-SNAPSHOT

---

pom.xml

fix: issue #428: delete fastjson version number

---

docs/docs/user_docs/getting-started/difference.md

- Replace surveillance pictures

Replace surveillance pictures

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/condition/PrometheusMonitorCondition.java

add dot for prometheus condition matches

---

hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/remote/AbstractHealthCheck.java

Optimize client health check time delay mechanism

---

hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/monitor/ReportingEventExecutor.java

Code formatting

---

docs/docs/user_docs/intro.md

- Remove custom log component (#460)

Remove custom log component

---

hippo4j-message/src/main/java/cn/hippo4j/message/platform/WeChatSendMessageHandler.java

- Fix reading wrong config change files

Fix reading wrong config change files

---

hippo4j-adapter/hippo4j-adapter-base/pom.xml
hippo4j-auth/pom.xml
hippo4j-common/pom.xml
hippo4j-config/pom.xml
hippo4j-core/pom.xml
hippo4j-discovery/pom.xml
hippo4j-message/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter/pom.xml
pom.xml

Fixes #463 
- Murphy Security Bug List Fixes

Murphy Security Bug List Fixes

---

hippo4j-adapter/hippo4j-adapter-spring-cloud-stream-rocketmq/pom.xml
hippo4j-console/pom.xml
hippo4j-discovery/pom.xml
hippo4j-server/pom.xml
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-dubbo/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-hystrix/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-kafka/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-rabbitmq/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-rocketmq/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-kafka/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rocketmq/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-web/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter/pom.xml
pom.xml

- Combing root pom portable dependencies

Combing root pom portable dependencies

---

hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/DynamicThreadPoolPostProcessor.java

Fixes #475
- Subscription callback thread pool parameter changes

Subscription callback thread pool parameter changes

---

hippo4j-common/src/main/java/cn/hippo4j/common/model/ThreadDetailStateInfo.java
hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/BooleanUtil.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/impl/NotifyServiceImpl.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/config/BootstrapProperties.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/config/DiscoveryConfiguration.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/config/NettyClientConfiguration.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/controller/WebThreadPoolController.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/controller/WebThreadPoolRunStateController.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/BaseThreadDetailStateHandler.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/CacheData.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ConfigEmptyAnalyzer.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ConfigService.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/DiscoveryClient.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/DynamicThreadPoolPostProcessor.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ServerThreadPoolDynamicRefresh.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ThreadPoolAdapterRegister.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ThreadPoolConfigService.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ThreadPoolOperation.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/monitor/ReportingEventExecutor.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/monitor/send/netty/NettyConnectSender.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/notify/ServerNotifyConfigBuilder.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/remote/AbstractHealthCheck.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/security/SecurityProxy.java

- hippo4j-spring-boot-starter code naming and log optimization

hippo4j-spring-boot-starter code naming and log optimization

---

hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/BooleanUtil.java

- Add open source protocol headers

Add open source protocol headers

---

hippo4j-common/src/main/java/cn/hippo4j/common/model/ThreadPoolParameterInfo.java
hippo4j-message/src/main/java/cn/hippo4j/message/request/ChangeParameterNotifyRequest.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/common/ConfigFileTypeEnum.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/BootstrapCoreProperties.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/ExecutorProperties.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/NotifyPlatformProperties.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/WebThreadPoolProperties.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/monitor/DynamicThreadPoolMonitorExecutor.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/notify/CoreNotifyConfigBuilder.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/parser/AbstractConfigParser.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/parser/ConfigFileTypeEnum.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/parser/ConfigParser.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/parser/ConfigParserHandler.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/parser/PropertiesConfigParser.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/parser/YamlConfigParser.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/AbstractCoreThreadPoolDynamicRefresh.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/ApolloRefresherHandler.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/BootstrapCorePropertiesBinderAdapt.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/NacosCloudRefresherHandler.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/NacosRefresherHandler.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/ZookeeperRefresherHandler.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/ExecutorsListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/Hippo4jCoreDynamicRefreshEvent.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/Hippo4jCoreDynamicRefreshEventOrder.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/PlatformsListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/WebExecutorListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/support/DynamicThreadPoolPostProcessor.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/support/GlobalCoreThreadPoolManage.java

- hippo4j-core-spring-boot-starter code naming and log optimization

hippo4j-core-spring-boot-starter code naming and log optimization

---

hippo4j-discovery/src/main/java/cn/hippo4j/discovery/config/RegistryConfiguration.java
hippo4j-discovery/src/main/java/cn/hippo4j/discovery/controller/ApplicationController.java
hippo4j-discovery/src/main/java/cn/hippo4j/discovery/core/BaseInstanceRegistry.java
hippo4j-discovery/src/main/java/cn/hippo4j/discovery/core/ClientCloseHookRemoveNode.java
hippo4j-discovery/src/main/java/cn/hippo4j/discovery/core/InstanceRegistry.java
hippo4j-discovery/src/main/java/cn/hippo4j/discovery/core/Lease.java

- hippo4j-discovery code naming and log optimization

hippo4j-discovery code naming and log optimization

---

hippo4j-monitor/hippo4j-monitor-base/pom.xml
hippo4j-monitor/hippo4j-monitor-base/src/main/java/com/example/monitor/base/MonitorTypeEnum.java
hippo4j-monitor/hippo4j-monitor-es/pom.xml
hippo4j-monitor/hippo4j-monitor-es/src/main/java/cn/hippo4j/monitor/es/EsMonitorHandler.java
hippo4j-monitor/hippo4j-monitor-log/pom.xml
hippo4j-monitor/hippo4j-monitor-log/src/main/java/cn/hippo4j/monitor/log/LogMonitorHandler.java
hippo4j-monitor/hippo4j-monitor-prometheus/pom.xml
hippo4j-monitor/hippo4j-monitor-prometheus/src/main/java/cn/hippo4j/monitor/prometheus/PrometheusMonitorHandler.java
hippo4j-monitor/pom.xml
pom.xml

- hippo4j-monitor code naming and log optimization

hippo4j-monitor code naming and log optimization

---

hippo4j-server/pom.xml
hippo4j-server/src/main/java/cn/hippo4j/server/listener/BaseSpringApplicationRunListener.java
hippo4j-server/src/main/java/cn/hippo4j/server/listener/Hippo4JApplicationListener.java
hippo4j-server/src/main/java/cn/hippo4j/server/listener/StartingApplicationListener.java

- hippo4j-server code naming and log optimization

hippo4j-server code naming and log optimization

---

hippo4j-adapter/hippo4j-adapter-base/src/main/java/cn/hippo4j/adapter/base/ThreadPoolAdapterRegisterAction.java
hippo4j-adapter/hippo4j-adapter-dubbo/pom.xml
hippo4j-adapter/hippo4j-adapter-dubbo/src/main/java/cn/hippo4j/adapter/dubbo/DubboThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-hystrix/src/main/java/cn/hippo4j/adapter/hystrix/HystrixThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-kafka/pom.xml
hippo4j-adapter/hippo4j-adapter-rabbitmq/src/main/java/cn/hippo4j/adapter/rabbitmq/RabbitMQThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-rocketmq/pom.xml
hippo4j-adapter/hippo4j-adapter-rocketmq/src/main/java/cn/hippo4j/adapter/rocketmq/RocketMQThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-spring-cloud-stream-kafka/pom.xml
hippo4j-adapter/hippo4j-adapter-spring-cloud-stream-rocketmq/pom.xml
hippo4j-adapter/hippo4j-adapter-spring-cloud-stream-rocketmq/src/main/java/cn/hippo4j/adapter/springcloud/stream/rocketmq/SpringCloudStreamRocketMQThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-web/pom.xml
hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/AbstractWebThreadPoolService.java
hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/JettyWebThreadPoolHandler.java
hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/TomcatWebThreadPoolHandler.java
hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/UndertowWebThreadPoolHandler.java
hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/WebThreadPoolRunStateHandler.java

- hippo4j-adapter code naming and log optimization

hippo4j-adapter code naming and log optimization

---

hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/TomcatWebThreadPoolHandler.java
hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/UndertowWebThreadPoolHandler.java
hippo4j-common/src/main/java/cn/hippo4j/common/constant/ChangeThreadPoolConstants.java
hippo4j-common/src/main/java/cn/hippo4j/common/design/observer/AbstractSubjectCenter.java
hippo4j-config/src/main/java/cn/hippo4j/config/notify/DefaultPublisher.java
hippo4j-config/src/main/java/cn/hippo4j/config/notify/NotifyCenter.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/ConfigCacheService.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/LongPollingService.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/impl/ConfigServiceImpl.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/handler/ClientCloseHookRemoveConfigCache.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/handler/RemoveThreadPoolAdapterCache.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/AbstractBuildThreadPoolTemplate.java
hippo4j-discovery/src/main/java/cn/hippo4j/discovery/controller/ApplicationController.java
hippo4j-discovery/src/main/java/cn/hippo4j/discovery/core/BaseInstanceRegistry.java
hippo4j-example/hippo4j-example-core/src/main/java/cn/hippo4j/example/core/inittest/TaskDecoratorTest.java
hippo4j-message/src/main/java/cn/hippo4j/message/service/Hippo4jBaseSendMessageService.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/ExecutorsListener.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ServerThreadPoolDynamicRefresh.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/toolkit/HttpClientUtil.java

- Log print content optimization

Log print content optimization

---

hippo4j-common/src/main/java/cn/hippo4j/common/constant/ChangeThreadPoolConstants.java

- Dynamic thread pool parameter change Copywriting modification

Dynamic thread pool parameter change Copywriting modification

---

hippo4j-adapter/hippo4j-adapter-base/pom.xml
hippo4j-adapter/hippo4j-adapter-hystrix/pom.xml
hippo4j-adapter/hippo4j-adapter-rabbitmq/pom.xml
hippo4j-common/pom.xml
hippo4j-example/hippo4j-spring-boot-starter-adapter-rocketmq-example/pom.xml
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-all/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-dubbo/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-hystrix/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-kafka/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-rabbitmq/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-rocketmq/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-kafka/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rocketmq/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-web/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-monitor/hippo4j-spring-boot-starter-monitor-es/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-monitor/hippo4j-spring-boot-starter-monitor-log/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-monitor/hippo4j-spring-boot-starter-monitor-prometheus/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter/pom.xml
pom.xml

- Delete useless blank lines from pom file

Delete useless blank lines from pom file

---

hippo4j-config/src/main/java/cn/hippo4j/config/notify/DefaultPublisher.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/ThreadPoolNotifyAlarmHandler.java
hippo4j-message/src/main/java/cn/hippo4j/message/service/ThreadPoolNotifyAlarm.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/notify/CoreNotifyConfigBuilder.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/ZookeeperRefresherHandler.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/ExecutorsListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/support/DynamicThreadPoolPostProcessor.java

- Change the name of the alarm field

Change the name of the alarm field

---

hippo4j-adapter/hippo4j-adapter-rabbitmq/pom.xml

File formatting

---

hippo4j-common/src/main/java/cn/hippo4j/common/model/register/DynamicThreadPoolRegisterWrapper.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/DynamicThreadPoolService.java
hippo4j-example/hippo4j-example-core/src/main/java/cn/hippo4j/example/core/inittest/RegisterDynamicThreadPoolTest.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/DynamicThreadPoolConfigService.java

- Change thread pool dynamic registration logic

Change thread pool dynamic registration logic

---

hippo4j-monitor/hippo4j-monitor-es/src/main/java/cn/hippo4j/monitor/es/EsMonitorHandler.java

fix es deprecated method

---

hippo4j-example/hippo4j-spring-boot-starter-es-monitor-example/pom.xml
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter/pom.xml

old version monitor compatible

---

hippo4j-config/src/main/java/cn/hippo4j/config/config/MyMetaObjectHandler.java

optimize mybatisPlus config #501

---

hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/ReflectUtil.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/manage/GlobalThreadPoolManage.java
hippo4j-example/hippo4j-example-core/pom.xml
hippo4j-example/hippo4j-example-core/src/main/java/cn/hippo4j/example/core/config/ThreadPoolConfig.java
hippo4j-example/hippo4j-example-core/src/main/java/cn/hippo4j/example/core/inittest/RegisterDynamicThreadPoolTest.java

- Thread pool dynamic registration optimization

Thread pool dynamic registration optimization

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/adpter/DynamicThreadPoolAdapter.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/adpter/DynamicThreadPoolAdapterChoose.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/adpter/TransmittableThreadLocalExecutorAdapter.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/adpter/TransmittableThreadLocalExecutorServiceAdapter.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/DynamicThreadPoolPostProcessor.java

Fixes #506
- Ali TTL framework thread pool adaptation (#506)

Ali TTL framework thread pool adaptation (#506)

---

hippo4j-common/src/main/java/cn/hippo4j/common/model/register/DynamicThreadPoolRegisterParameter.java
hippo4j-common/src/main/java/cn/hippo4j/common/model/register/DynamicThreadPoolRegisterWrapper.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/DynamicThreadPoolSubscribeConfig.java

- Open source protocol header file addition

Open source protocol header file addition

---

hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/support/DynamicThreadPoolPostProcessor.java

- hippo4j core adapts to Ali ttl 

hippo4j core adapts to Ali ttl

---

hippo4j-common/src/main/java/cn/hippo4j/common/model/register/notify/DynamicThreadPoolRegisterCoreNotifyParameter.java
hippo4j-common/src/main/java/cn/hippo4j/common/model/register/notify/DynamicThreadPoolRegisterServerNotifyParameter.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/service/AbstractDynamicThreadPoolService.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/BootstrapCorePropertiesBinderAdapt.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/support/DynamicThreadPoolConfigService.java

Style formatting

---

hippo4j-config/src/main/java/cn/hippo4j/config/service/ThreadPoolAdapterService.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/DynamicThreadPoolNotifyProperties.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/config/ExecutorProperties.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/notify/CoreNotifyConfigBuilder.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/BootstrapCorePropertiesBinderAdapt.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/ZookeeperRefresherHandler.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/AdapterExecutorsRefreshListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/DynamicThreadPoolRefreshListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/PlatformsRefreshListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/refresher/event/WebExecutorRefreshListener.java
hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/support/DynamicThreadPoolPostProcessor.java

- Adjust hippo4j-core module properties

Adjust hippo4j-core module properties

---

hippo4j-common/src/main/java/cn/hippo4j/common/model/register/DynamicThreadPoolRegisterWrapper.java
hippo4j-common/src/main/java/cn/hippo4j/common/model/register/notify/DynamicThreadPoolRegisterServerNotifyParameter.java
hippo4j-config/src/main/java/cn/hippo4j/config/model/biz/notify/NotifyReqDTO.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/NotifyService.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/impl/ConfigServiceImpl.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/impl/NotifyServiceImpl.java
hippo4j-example/hippo4j-example-core/src/main/java/cn/hippo4j/example/core/inittest/RegisterDynamicThreadPoolTest.java

- hippo4j server add dynamic registration notification alarm

hippo4j server add dynamic registration notification alarm

---

hippo4j-common/src/main/java/cn/hippo4j/common/spi/DynamicThreadPoolServiceLoader.java
hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/MessageConvert.java

delete deprecated api

---

hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/impl/ThreadPoolServiceImpl.java

Fixes #[537](https://github.com/opengoofy/hippo4j/issues/537)
- The timeout period is configured to repair NPE

fix(hippo4j-server): The timeout period is configured to repair NPE

---

hippo4j-adapter/hippo4j-adapter-rabbitmq/src/main/java/cn/hippo4j/adapter/rabbitmq/RabbitMQThreadPoolAdapter.java
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-rabbitmq/src/main/java/cn/hippo4j/springboot/starter/adapter/rabbitmq/RabbitMQAdapterAutoConfiguration.java

Fixes： #https://github.com/opengoofy/hippo4j/issues/533
Support rabbitmq multi-connection

Support rabbitmq multi-connection

---

docs/docs/user_docs/user_guide/server-docker.md
hippo4j-server/Dockerfile
hippo4j-server/pom.xml

Fixes #206 
- add hippo4j-server dockerfile 

feat: add docker file. close #206

---

docs/docs/user_docs/ops/server-docker.md
hippo4j-server/Dockerfile

- Only the datasource parameter is exposed

feat: Only the datasource parameter is exposed

---

docs/docs/user_docs/ops/server-docker.md
hippo4j-server/Dockerfile

- dockerfile datasource host port db exposed.

feat: dockerfile datasource host port db exposed.

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/ThreadFactoryBuilder.java

Optimize the thread name produced by thread pool factory

---

docs/docs/community/developer.md
hippo4j-adapter/hippo4j-adapter-spring-cloud-stream-rabbitmq/pom.xml
hippo4j-adapter/hippo4j-adapter-spring-cloud-stream-rabbitmq/src/main/java/cn/hippo4j/adapter/springcloud/stream/rabbitmq/SpringCloudStreamRabbitMQThreadPoolAdapter.java
hippo4j-adapter/pom.xml
hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq-example/pom.xml
hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq-example/src/main/java/cn/hippo4j/springboot/starter/adapter/springcloud/stream/rabbitmq/example/MessageProduce.java
hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq-example/src/main/java/cn/hippo4j/springboot/starter/adapter/springcloud/stream/rabbitmq/example/ServerAdapterSpringCloudStreamRabbitMQApplication.java
hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq-example/src/main/resources/application.properties
hippo4j-example/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq/src/main/java/cn/hippo4j/springboot/starter/adapter/springcloud/stream/rabbitmq/SpringCloudStreamRabbitMQAdapterAutoConfiguration.java
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq/src/main/resources/META-INF/spring.factories
hippo4j-spring-boot/hippo4j-spring-boot-starter-adapter/pom.xml
pom.xml

Fixes  #232
- add support spring-cloud-stream-rabbitmq

feat: add support spring-cloud-stream-rabbitmq

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/ThreadPoolBuilder.java

Fixes #569
- fix: only set capacity, capacity is invalid.

fix: only set capacity, capacity is invalid.

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/question-report.md

ISSUE_TEMPLATE:  Hippo-4J Core -> Hippo-4J Config

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/BooleanUtilTest.java

feat: BooleanUtilTest 补充测试用例

---

hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/ReflectUtil.java

Fixes  #589 
- fix:  ReflectUtil#getFieldsDirectly missing fields

 ReflectUtil#getFieldsDirectly missing fields

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/FileUtilTest.java
hippo4j-common/src/test/resources/test/test_utf8.txt

complete FileUtil test case (#587)

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/ConditionUtilTest.java

Fixes #585
Complete ConditionUtilTest test cases
- 

Complete ConditionUtilTest test cases (#585)

---

hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/ByteConvertUtil.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/ByteConvertUtilTest.java

fix:内存大小单位转换修复

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/AbstractBuildThreadPoolTemplate.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/ThreadPoolBuilder.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/adpter/DynamicThreadPoolAdapterChoose.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/adpter/ThreadPoolTaskExecutorAdapter.java
hippo4j-example/hippo4j-example-core/src/main/java/cn/hippo4j/example/core/config/DynamicThreadPoolConfig.java
hippo4j-example/hippo4j-example-core/src/main/java/cn/hippo4j/example/core/inittest/RunStateHandlerTest.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/core/springboot/starter/support/DynamicThreadPoolPostProcessor.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/support/DynamicThreadPoolPostProcessor.java

Fixes #606
- Support Spring ThreadPoolTaskExecutor

Support Spring ThreadPoolTaskExecutor

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/ArrayUtilTest.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/CalculateUtilTest.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/CollectionUtilTest.java

test: add ut

---

hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/UndertowWebThreadPoolHandler.java

Fix the UndertowWeb adaptation

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/JSONUtilTest.java

Complete JSONUtilTest test cases (#628)

---

hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq-example/pom.xml
hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq-example/src/main/java/cn/hippo4j/springboot/starter/adapter/springcloud/stream/rabbitmq/example/MessageProduce.java
hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq-example/src/main/java/cn/hippo4j/springboot/starter/adapter/springcloud/stream/rabbitmq/example/ServerAdapterSpringCloudStreamRabbitMQApplication.java
hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rocketmq-example/src/main/java/cn/hippo4j/springboot/starter/adapter/springcloud/stream/rocketmq/example/MessageConsume.java
hippo4j-example/hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rocketmq-example/src/main/java/cn/hippo4j/springboot/starter/adapter/springcloud/stream/rocketmq/example/MessageProduce.java

replace fastjson to JSONUtil

---

hippo4j-console/src/main/java/cn/hippo4j/console/controller/ThreadPoolController.java

Fix issue 638

---

hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/AdapterExecutorProperties.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/BootstrapConfigProperties.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/ConfigHandlerConfiguration.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/DynamicThreadPoolCoreAutoConfiguration.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/ExecutorProperties.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/AbstractRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/AdapterExecutorsRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/DynamicThreadPoolRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/PlatformsRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/RefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/WebExecutorRefreshListener.java

fix: filter nodes that do not require a dynamic refresh (#614)

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/ContentUtilTest.java

Add unit test cases

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/StringUtilTest.java

Fixes #643
add StringUtilTest JUnit test case

add StringUtilTest JUnit test case

---

hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/AbstractRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/AdapterExecutorsRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/DynamicThreadPoolRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/WebExecutorRefreshListener.java

Redefine the behavior of base and subclasses

fix : Redefine the behavior of base and subclasses

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/ThreadUtilTest.java

add junit test case #644

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/FileUtilTest.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/ThreadUtilTest.java

fix FileUtilTest junit test case run error

fix FileUtilTest junit test case run error

---

hippo4j-common/src/main/java/cn/hippo4j/common/model/WebIpAndPortInfo.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/AbstractRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/AdapterExecutorsRefreshListener.java

improve the way to get port and ip

improve the way to get port and ip

---

hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/DynamicThreadPoolAutoConfiguration.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/resources/META-INF/spring.factories

design and modify documents,DynamicThreadPoolAutoConfiguration

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/FileUtilTest.java

add FileUtilTest test case

---

hippo4j-config/src/main/java/cn/hippo4j/config/config/MybatisPlusConfig.java

assign profilesActive default value in MybatisPlusConfig

---

hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/support/DynamicThreadPoolPostProcessor.java

remove useless temporary variables in DynamicThreadPoolPostProcessor

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/FileUtilTest.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/Md5UtilTest.java

add Md5UtilTest test case

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/UserContextTest.java

Fixes #645 
complete UserContextTest test

complete UserContextTest test case #645

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/ReflectUtilTest.java

add ReflectUtilTest test case (#641)

---

hippo4j-config/src/test/java/cn/hippo4j/config/toolkit/MapUtilTest.java

add MapUtilTest test case

---

hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/SingletonTest.java

add SingletonTest test case(#642)

---

hippo4j-config/src/test/java/cn/hippo4j/config/toolkit/BeanUtilTest.java

add BeanUtilTest test case

---

hippo4j-config/src/test/java/cn/hippo4j/config/toolkit/BeanUtilTest.java
hippo4j-config/src/test/java/cn/hippo4j/config/toolkit/ClassUtilTest.java

add ClassUtilTest test case

---

hippo4j-config/src/test/java/cn/hippo4j/config/toolkit/SimpleReadWriteLockTest.java
hippo4j-server/pom.xml

https://github.com/opengoofy/hippo4j/issues/712

remove redundant dependencies

---

hippo4j-adapter/hippo4j-adapter-base/src/main/java/cn/hippo4j/adapter/base/ThreadPoolAdapterBeanContainer.java
hippo4j-config/src/test/java/cn/hippo4j/config/toolkit/BeanUtilTest.java
hippo4j-config/src/test/java/cn/hippo4j/config/toolkit/ClassUtilTest.java
hippo4j-config/src/test/java/cn/hippo4j/config/toolkit/ConfigExecutorTest.java

add ConfigExecutorTest test case

---

hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/WebIpAndPortHolder.java
hippo4j-common/src/main/java/cn/hippo4j/common/api/ThreadPoolInitRefresh.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/AdapterExecutorProperties.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/WebThreadPoolProperties.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/AbstractConfigThreadPoolDynamicRefresh.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/ApolloRefresherHandler.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/EtcdRefresherHandler.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/NacosCloudRefresherHandler.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/NacosRefresherHandler.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/ZookeeperRefresherHandler.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/AbstractRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/AdapterExecutorsRefreshListener.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/event/WebExecutorRefreshListener.java

Adapter 初始化覆盖核心参数

---

hippo4j-adapter/hippo4j-adapter-dubbo/src/main/java/cn/hippo4j/adapter/dubbo/DubboThreadPoolAdapter.java

Fixes #708
- Fixed a version compatibility issue with the Dubbo Thread Pool fetch method

 Fixed a version compatibility issue with the Dubbo Thread Pool fetch method

---

hippo4j-common/src/test/java/cn/hippo4j/common/function/MatcherFunctionTest.java

add MatcherFunctionTest test case

---

hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/GroupKey.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/GroupKeyTest.java

Add test case for GroupKey.java

---

docs/docs/user_docs/ops/server-docker.md
hippo4j-server/Dockerfile
hippo4j-server/conf/hippo4j-logback.xml
hippo4j-server/docker-startup.sh

Fixes #723
- docker support mysql and h2

docker support mysql and h2

---

hippo4j-common/src/test/java/cn/hippo4j/common/function/NoArgsConsumerTest.java

Add test case for NoArgsConsumer

---

hippo4j-common/src/test/java/cn/hippo4j/common/function/MatcherFunctionTest.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/pom.xml
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/config/ConfigHandlerConfiguration.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/refresher/PolarisRefresherHandler.java
pom.xml

Fixes https://github.com/opengoofy/hippo4j/issues/748

add PolarisRefresherHandler

---

hippo4j-common/src/test/java/cn/hippo4j/common/function/MatcherFunctionTest.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/ThreadPoolBuilder.java
hippo4j-example/hippo4j-config-etcd-spring-boot-starter-example/src/main/java/cn/hippo4j/example/config/etcd/config/ThreadPoolConfig.java

Simplified thread pool creation

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/DynamicThreadPool.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/SpringDynamicThreadPool.java
hippo4j-example/hippo4j-config-etcd-spring-boot-starter-example/src/main/java/cn/hippo4j/example/config/etcd/config/ThreadPoolConfig.java
hippo4j-example/hippo4j-example-core/src/main/java/cn/hippo4j/example/core/config/DynamicThreadPoolConfig.java

Simplified DynamicThreadPool usage

---

hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/ReflectUtil.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/ReflectUtilTest.java

fix : solve ReflectUtil#getMethodByName IllegalException (#763)

---

hippo4j-auth/src/main/java/cn/hippo4j/auth/config/GlobalSecurityConfig.java
hippo4j-auth/src/main/java/cn/hippo4j/auth/filter/JWTAuthenticationFilter.java
hippo4j-auth/src/main/java/cn/hippo4j/auth/service/impl/UserDetailsServiceImpl.java
hippo4j-core/src/main/java/cn/hippo4j/core/enable/BeforeCheckConfiguration.java
hippo4j-example/hippo4j-spring-boot-starter-example/src/main/resources/application.properties
hippo4j-server/src/main/resources/application.properties
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/remote/HttpScheduledHealthCheck.java

Fixes #60
>注意: 由于前端页面校验问题,随机输入密码即可. 待前端校验去除后无需输入密码即可登录

feat: Added authentication mode on the server side

---

hippo4j-server/conf/application.properties
hippo4j-server/src/main/resources/application.properties

Add note
```
hippo4j.core.auth.enabled=false
```

Add note for Authentication

---

hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/StringUtil.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/StringUtilTest.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/ThreadPoolAdapterService.java
hippo4j-console/src/main/java/cn/hippo4j/console/controller/ThreadPoolAdapterController.java
hippo4j-console/src/main/java/cn/hippo4j/console/controller/ThreadPoolController.java
hippo4j-message/src/main/java/cn/hippo4j/message/platform/WeChatSendMessageHandler.java

New feature

---

hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/impl/AbstractConfigModificationVerifyService.java

fix bug #783

---

hippo4j-common/pom.xml
hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/HttpClientUtil.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/HttpClientUtilTest.java
hippo4j-config/pom.xml
hippo4j-config/src/main/java/cn/hippo4j/config/service/ThreadPoolAdapterService.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/impl/AdapterThreadPoolConfigModificationVerifyServiceImpl.java
hippo4j-config/src/main/java/cn/hippo4j/config/service/biz/impl/WebThreadPoolConfigModificationVerifyServiceImpl.java
hippo4j-console/src/main/java/cn/hippo4j/console/controller/ThreadPoolAdapterController.java
hippo4j-console/src/main/java/cn/hippo4j/console/controller/ThreadPoolController.java
hippo4j-message/src/main/java/cn/hippo4j/message/platform/LarkSendMessageHandler.java
hippo4j-message/src/main/java/cn/hippo4j/message/platform/WeChatSendMessageHandler.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/pom.xml
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/config/HttpClientConfiguration.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/remote/ServerHttpAgent.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/security/SecurityProxy.java

Replace RestTemplate with HttpClientUtil

---

docs/docs/user_docs/getting_started/server/hippo4j-server-start.md

docs:delete redundancy rows

---

hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/support/DynamicThreadPoolConfigService.java

feat:register throws error message

---

hippo4j-common/src/main/java/cn/hippo4j/common/executor/ThreadPoolManager.java
hippo4j-common/src/test/java/cn/hippo4j/common/executor/ThreadPoolManagerTest.java

fix : supplement unit test for ThreadPoolManager

---

hippo4j-auth/src/test/java/cn/hippo4j/auth/secuity/JwtTokenManagerTest.java

Fixes #734
- JwtTokenManagerTest add test case

JwtTokenManagerTest add test case

---

hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java

early method return

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/ThreadPoolBuilder.java

The core thread must not be larger than the maximum thread.

---

hippo4j-common/src/main/java/cn/hippo4j/common/constant/HttpResponseCode.java
hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/http/HttpUtil.java
hippo4j-server/hippo4j-config/src/main/java/cn/hippo4j/config/service/LongPollingService.java

Long polling returns the appropriate status code

---

hippo4j-common/src/main/java/cn/hippo4j/common/toolkit/JSONUtil.java
hippo4j-common/src/test/java/cn/hippo4j/common/toolkit/JSONUtilTest.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/DynamicThreadPoolWrapper.java
hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/support/DynamicThreadPoolPostProcessor.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/DynamicThreadPoolSubscribeConfig.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/support/DynamicThreadPoolPostProcessor.java

default subscribe to the remote thread pool configuration.

---

hippo4j-core/pom.xml
hippo4j-core/src/test/java/cn/hippo4j/core/executor/DynamicThreadPoolExecutorTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/executor/ExtensibleThreadPoolExecutorTest.java

Add unit test for DynamicThreadPoolExecutor and ExtensibleThreadPoolExecutor
- 

Add unit test for DynamicThreadPoolExecutor and ExtensibleThreadPoolExecutor

---

hippo4j-core/src/main/java/cn/hippo4j/core/plugin/impl/AbstractTaskTimerPlugin.java
hippo4j-core/src/main/java/cn/hippo4j/core/plugin/impl/TaskTimeRecordPlugin.java
hippo4j-core/src/main/java/cn/hippo4j/core/plugin/impl/TaskTimeoutNotifyAlarmPlugin.java

Extract the logic about calculating task execution time to superclass (#879)

---

docs/docs/community/developer.md

doc: Update developer

---

hippo4j-core/src/test/java/cn/hippo4j/core/plugin/manager/DefaultThreadPoolPluginManagerTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/manager/DefaultThreadPoolPluginRegistrarTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/manager/EmptyThreadPoolPluginManagerTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/manager/ThreadPoolPluginSupportTest.java

Add unit test about plugin manager
- 

Add unit test about plugin manager

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/DynamicThreadPool.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/FastThreadPoolExecutor.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/TaskQueue.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/ThreadPoolBuilder.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/support/ThreadPoolExecutorTemplate.java

- Supplemental code comments. 

Supplemental code comments

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/ThreadPoolNotifyAlarmHandler.java

Fix checkPoolActivityAlarm bug

---

hippo4j-core/src/test/java/cn/hippo4j/core/plugin/PluginRuntimeTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/ThreadPoolPluginTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/impl/TaskDecoratorPluginTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/impl/TaskRejectCountRecordPluginTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/impl/TaskRejectNotifyAlarmPluginTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/impl/TaskTimeRecordPluginTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/impl/TaskTimeoutNotifyAlarmPluginTest.java
hippo4j-core/src/test/java/cn/hippo4j/core/plugin/impl/ThreadPoolExecutorShutdownPluginTest.java

[Fixes #ISSUSE_ID](test: add test for plugins)
- 

test: add test for plugins

---

hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/java/cn/hippo4j/config/springboot/starter/support/DynamicThreadPoolPostProcessor.java
hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/support/DynamicThreadPoolPostProcessor.java

Fixes #874
- Spring post processor logic refactoring

Spring post processor logic refactoring

---

hippo4j-core/src/main/java/cn/hippo4j/core/executor/DynamicThreadPoolExecutor.java
hippo4j-core/src/main/java/cn/hippo4j/core/executor/ExtensibleThreadPoolExecutor.java
hippo4j-core/src/main/java/cn/hippo4j/core/toolkit/inet/InetUtils.java
hippo4j-server/hippo4j-config/src/main/java/cn/hippo4j/config/rpc/support/NettyConnectPoolHolder.java

Format code

---

hippo4j-core/src/test/java/cn/hippo4j/core/handler/DynamicThreadPoolBannerHandlerTest.java

- DynamicThreadPoolBannerHandlerTest.java

Add DynamicThreadPoolBannerHandlerTest

---

dev-support/hippo4j_checkstyle_suppression.xml
hippo4j-adapter/hippo4j-adapter-hystrix/src/main/java/cn/hippo4j/adapter/hystrix/HystrixThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-rabbitmq/src/main/java/cn/hippo4j/adapter/rabbitmq/RabbitMQThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-rocketmq/src/main/java/cn/hippo4j/adapter/rocketmq/RocketMQThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-spring-cloud-stream-rabbitmq/src/main/java/cn/hippo4j/adapter/springcloud/stream/rabbitmq/SpringCloudStreamRabbitMQThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-spring-cloud-stream-rocketmq/src/main/java/cn/hippo4j/adapter/springcloud/stream/rocketmq/SpringCloudStreamRocketMQThreadPoolAdapter.java
hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/TomcatWebThreadPoolHandler.java
hippo4j-adapter/hippo4j-adapter-web/src/main/java/cn/hippo4j/adapter/web/WebIpAndPortHolder.java

hippo4j-adapter CheckStyle ERROR
